# Generated by Django 3.2.25 on 2024-04-17 08:06

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20240415_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
